"use client";

import { useState } from "react";
import { CLUB_TEAMS } from "@/lib/teams";
import { Upload, CheckCircle2, AlertTriangle, Loader2 } from "lucide-react";

type Row = { sourceIndex:number; category:string; team:string; opponent:string; matchDate:string; location:string; isHome:boolean; competitionKey:string; competitionLabel:string; confidence:string; warning?:string; existingMatch:null | {id:string; matchDate:string; location:string; isHome:boolean; competitionKey:string; competitionLabel:string}; selected?:boolean; state?:"idle"|"creating"|"created"|"error"; error?:string };

function categoryFor(team:string){ if(team.startsWith("Seniors")) return "Seniors"; if(team.startsWith("U15")) return "U15"; if(team.startsWith("U13")) return "U13"; return team; }

export default function MatchProgramImporter(){
 const [file,setFile]=useState<File|null>(null); const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function analyze(){ if(!file)return; setLoading(true);setError("");setRows([]); const fd=new FormData();fd.append("file",file); try{const res=await fetch("/api/admin/match-import/analyze",{method:"POST",body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||"Analyse impossible.");setRows(data.matches.map((r:Row)=>({...r,selected:!r.existingMatch,state:"idle"})));}catch(e){setError(e instanceof Error?e.message:"Analyse impossible.");}finally{setLoading(false);} }
 function patch(i:number,changes:Partial<Row>){setRows(v=>v.map((r,n)=>n===i?{...r,...changes}:r));}
 async function createSelected(){for(let i=0;i<rows.length;i++){const r=rows[i];if(!r.selected||r.existingMatch||r.state==="created")continue;patch(i,{state:"creating",error:""});try{const res=await fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:r.category||categoryFor(r.team),team:r.team,opponent:r.opponent,matchDate:r.matchDate,location:r.location,isHome:r.isHome,status:"scheduled",competitionKey:r.competitionKey,scoreTeam:null,scoreOpponent:null,scorers:null})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Création impossible.");patch(i,{state:"created",selected:false});}catch(e){patch(i,{state:"error",error:e instanceof Error?e.message:"Erreur"});}}
 }
 const missing=rows.filter(r=>!r.existingMatch&&r.state!=="created").length; const existing=rows.filter(r=>r.existingMatch).length;
 return <div className="mt-6 space-y-5">
  <section className="rounded-[1.75rem] border border-neutral-200 bg-white p-5 shadow-sm md:p-6"><h2 className="text-xl font-black">1. Déposer le PDF</h2><p className="mt-1 text-sm text-neutral-500">Le PDF reste un contrôle : aucun match n’est créé sans ta validation.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="input flex-1"/><button onClick={analyze} disabled={!file||loading} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-neutral-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{loading?<Loader2 className="animate-spin" size={17}/>:<Upload size={17}/>} Analyser le programme</button></div>{error?<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>:null}</section>
  {rows.length?<section className="rounded-[1.75rem] border border-neutral-200 bg-white p-5 shadow-sm md:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">2. Vérifier les rencontres</h2><p className="mt-1 text-sm text-neutral-500">{rows.length} détectée(s) · {existing} déjà présente(s) · {missing} manquante(s)</p></div><button onClick={createSelected} disabled={!rows.some(r=>r.selected&&!r.existingMatch)} className="rounded-2xl bg-orange-500 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Créer les matchs sélectionnés</button></div>
   <div className="mt-5 space-y-4">{rows.map((r,i)=><div key={r.sourceIndex} className={`rounded-2xl border p-4 ${r.existingMatch||r.state==="created"?"border-green-200 bg-green-50":"border-neutral-200"}`}><div className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-5 w-5" checked={Boolean(r.selected)} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>patch(i,{selected:e.target.checked})}/><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-xs font-black">{r.existingMatch?<span className="rounded-full bg-green-100 px-3 py-1 text-green-800">DÉJÀ PRÉSENT</span>:r.state==="created"?<span className="rounded-full bg-green-100 px-3 py-1 text-green-800">CRÉÉ</span>:<span className="rounded-full bg-orange-100 px-3 py-1 text-orange-800">À CRÉER</span>}{r.warning?<span className="inline-flex items-center gap-1 text-amber-700"><AlertTriangle size={13}/>{r.warning}</span>:null}</div>
    <div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-bold text-neutral-500">Équipe<select className="input mt-1" value={r.team} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>patch(i,{team:e.target.value,category:categoryFor(e.target.value)})}>{!r.team?<option value="">À choisir</option>:null}{CLUB_TEAMS.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-xs font-bold text-neutral-500">Adversaire<input className="input mt-1" value={r.opponent} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>patch(i,{opponent:e.target.value})}/></label><label className="text-xs font-bold text-neutral-500">Date / heure<input type="datetime-local" className="input mt-1" value={r.matchDate} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>patch(i,{matchDate:e.target.value})}/></label><label className="text-xs font-bold text-neutral-500">Lieu<input className="input mt-1" value={r.location} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>patch(i,{location:e.target.value})}/></label><label className="text-xs font-bold text-neutral-500">Terrain<select className="input mt-1" value={String(r.isHome)} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>{const isHome=e.target.value==="true";patch(i,{isHome,location:(r.location==="À confirmer"||r.location==="Stade BRICHON")?(isHome?"Stade BRICHON":"À confirmer"):r.location});}}><option value="true">Domicile</option><option value="false">Extérieur</option></select></label><label className="text-xs font-bold text-neutral-500">Compétition<select className="input mt-1" value={r.competitionKey} disabled={Boolean(r.existingMatch)||r.state==="created"} onChange={e=>patch(i,{competitionKey:e.target.value})}><option value="championship">Championnat</option><option value="coupe-france">Coupe de France</option><option value="coupe-laurafoot">Coupe LAuRAFoot</option><option value="coupe-ain">Coupe de l'Ain</option><option value="coupe-rene-morandas">Coupe René Morandas</option><option value="coupe-peggy-provost">Coupe Peggy Provost</option><option value="coupe-gambardella">Coupe Gambardella</option><option value="friendly">Match amical</option><option value="other">Autre</option></select></label></div>{r.existingMatch?<p className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-green-700"><CheckCircle2 size={16}/> Match déjà enregistré : aucune action nécessaire.</p>:null}{r.state==="creating"?<p className="mt-3 text-sm font-bold text-orange-600">Création…</p>:null}{r.state==="error"?<p className="mt-3 text-sm font-bold text-red-600">{r.error}</p>:null}{r.state==="created"?<p className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-green-700"><CheckCircle2 size={16}/> Match ajouté.</p>:null}</div></div></div>)}</div>
  </section>:null}
 </div>;
}
